version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:00"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:30"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "github-actions"
